-- MySQL Script generated by MySQL Workbench
-- Sat Oct  9 08:44:12 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema id17487746_proyecto2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id17487746_proyecto2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id17487746_proyecto2` DEFAULT CHARACTER SET utf8 ;
USE `id17487746_proyecto2` ;

-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`Cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(50) NOT NULL,
  `DPIAsociado` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `Cuenta_idCuenta` INT NOT NULL,
  `correo` VARCHAR(100) NULL,
  `telefono` VARCHAR(100) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Cuenta1_idx` (`Cuenta_idCuenta` ASC),
  CONSTRAINT `fk_Usuario_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `id17487746_proyecto2`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `Usuario` VARCHAR(100) NULL,
  `Password` VARCHAR(50) NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`Cajero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`Cajero` (
  `idCajero` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(100) NULL,
  `usuario` VARCHAR(100) NULL,
  `password` VARCHAR(50) NULL,
  `Administrador_idAdministrador` INT NOT NULL,
  PRIMARY KEY (`idCajero`),
  INDEX `fk_Cajero_Administrador1_idx` (`Administrador_idAdministrador` ASC),
  CONSTRAINT `fk_Cajero_Administrador1`
    FOREIGN KEY (`Administrador_idAdministrador`)
    REFERENCES `id17487746_proyecto2`.`Administrador` (`idAdministrador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
ALTER TABLE `id17487746_proyecto2`.`cajero` 
ADD COLUMN `activo` INT(1) NULL DEFAULT 1 AFTER `Administrador_idAdministrador`;

-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`detalle_cuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`detalle_cuenta` (
  `correlativo` INT NOT NULL AUTO_INCREMENT,
  `Cuenta_idCuenta` INT NOT NULL,
  `monto` DECIMAL(50,2) NULL,
  `fecha` DATETIME NULL,
  PRIMARY KEY (`correlativo`),
  INDEX `fk_detalle_cuenta_Cuenta1_idx` (`Cuenta_idCuenta` ASC),
  CONSTRAINT `fk_detalle_cuenta_Cuenta1`
    FOREIGN KEY (`Cuenta_idCuenta`)
    REFERENCES `id17487746_proyecto2`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`Transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`Transaccion` (
  `idTransaccion` INT NOT NULL AUTO_INCREMENT,
  `Cajero_idCajero` INT NOT NULL,
  `detalle_cuenta_correlativo` INT NOT NULL,
  `fecha` DATETIME NULL,
  `monto` DECIMAL(50,2) NULL,
  PRIMARY KEY (`idTransaccion`),
  INDEX `fk_Transaccion_Cajero1_idx` (`Cajero_idCajero` ASC),
  INDEX `fk_Transaccion_detalle_cuenta1_idx` (`detalle_cuenta_correlativo` ASC),
  CONSTRAINT `fk_Transaccion_Cajero1`
    FOREIGN KEY (`Cajero_idCajero`)
    REFERENCES `id17487746_proyecto2`.`Cajero` (`idCajero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Transaccion_detalle_cuenta1`
    FOREIGN KEY (`detalle_cuenta_correlativo`)
    REFERENCES `id17487746_proyecto2`.`detalle_cuenta` (`correlativo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id17487746_proyecto2`.`terceros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `id17487746_proyecto2`.`terceros` (
  `Correlativo` INT NOT NULL AUTO_INCREMENT,
  `principal` INT NOT NULL,
  `vinculada` INT NOT NULL,
  INDEX `fk_terceros_Cuenta1_idx` (`principal` ASC),
  INDEX `fk_terceros_Cuenta2_idx` (`vinculada` ASC),
  PRIMARY KEY (`Correlativo`),
  CONSTRAINT `fk_terceros_Cuenta1`
    FOREIGN KEY (`principal`)
    REFERENCES `id17487746_proyecto2`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_terceros_Cuenta2`
    FOREIGN KEY (`vinculada`)
    REFERENCES `id17487746_proyecto2`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
